name: Test cmake build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: '25.1'}
        include:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 12}

    steps:

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: cmake --version 

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Check compiler
      - run: |
      echo "Compiler from env: $FC"
      $FC --version
      echo "Compiler from output: ${{ steps.setup-fortran.outputs.fc }}"

      - name: Execute cmake and build for ${{matrix.toolchain.compiler}}
        run: |
          cmake -B build
          cmake --build build



